---
title: "Lab 4 - Writing Functions II"
author: "Cameron Kay & Ashley Miller"
date: "5/22/2019"
output: 
  html_document:
    theme: kate
    toc: yes
    toc_depth: 4
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

There are two parts to this lab. The first includes writing a relatively complicated function. The second involves using that function within a relatively basic shiny app.

## Part A: Writing a summary function

Write a function that takes a given data frame as its first argument, a grouping variable as its second argument, and a column to summarize as its third argument.

### Function behavior

By default, the function should report:

Total number of observations
* Number of non-missing observations
* Number of missing observations
* Mean
* Standard deviation
* Minimum
* Maximum

However, the function should be flexible so it can take any function(s) as its input to summarize by, provided the function results in a single value (e.g., anything you could feed to `dplyr::summarize`). You’ll need a fourth optional argument that lists the function(s) to use in the summary.

### Errors

Embed an error if

* Anything other than a data frame is supplied as the first argument
* The provided column to summarize is not numeric.

### Warnings

Embed a warning if

* The grouping variable is numeric (generally you would expect * the grouping variable to be a categorical variable)

### Some guidance

If you want to use {dplyr} you’ll need to use non-standard evaluation (NSE), so something like `!!enquo(group_var)`, where `group_var` is the formal argument of your function. If you go this route, you will also likely want to look into `summarize_*`, which take an additional .funs argument (to make the functions used in summarizing more flexible). Finally, dplyr::pull (together with NSE) will likely be helpful for checking types for warnings/errors.

Alternatively, you might consider `split`ing the dataset by the grouping variable, then looping over each split to apply the function(s) supplied.

### Sample output

See the [assignment page](https://rmarkdown.rstudio.com/authoring_basics.html) for the examples.

## Part B: Shiny app

Build a shiny app using the `gss_cat` dataset available through the {forcats} package, which you can access with `data(gss_cat, package = "forcats")`.

The app should allow the user to select a variable, including (potentially) “none”, and will produce a histogram of `tvhours` faceted by that variable. Below the plot, render a table summarizing the distributions using the function you wrote in Part A. Note, I would encourage you to take a look at `selectInput` rather than `radioButtons` for the categorical variable, but either should work.

For an example of what the shiny app should look like, see [here](https://djanderson07.shinyapps.io/lab-c3/).
